/*
 * @Author: dxx
 * @Date: 2022-12-22 15:10:07
 * @LastEditors: dxx
 * @LastEditTime: 2022-12-27 14:57:26
 */
export default [
  'icon-wisdom-arrawsalt',
  'icon-wisdom-shrink',
  'icon-wisdom-reloadtime',
  'icon-wisdom-dot',
  'icon-wisdom-menu-heatmap',
  'icon-wisdom-menu-layer',
  'icon-wisdom-menu-flag',
  'icon-wisdom-menu-home',
  'icon-wisdom-menu-map',
  'icon-wisdom-menu-brush',
  'icon-wisdom-menu-forklift',
  'icon-wisdom-menu-persons',
  'icon-wisdom-more',
  'icon-wisdom-menu-system',
  'icon-wisdom-menu-dispatch',
  'icon-wisdom-menu-device',
  'icon-wisdom-menu-logistics',
  'icon-wisdom-menu-focus',

  'icon-wisdom-guide',
  'icon-wisdom-upload',
  'icon-wisdom-download',
  'icon-wisdom-organization',
  'icon-wisdom-building',
  'icon-wisdom-publish',
  'icon-wisdom-road-network',
  'icon-wisdom-topology',
  'icon-wisdom-funnel',
  'icon-wisdom-yuanquan',
  'icon-wisdom-fence',
  'icon-wisdom-forklift-left',
  'icon-wisdom-eye-open',
  'icon-wisdom-eye-close',

  'icon-wisdom-pickup-fill',
  'icon-wisdom-pickup-line',
  'icon-wisdom-stowage-fill',
  'icon-wisdom-stowage-line',
  'icon-wisdom-logistics-car-fill',
  'icon-wisdom-logistics-car-line',
  'icon-wisdom-quality-fill',
  'icon-wisdom-quality-line',
  'icon-wisdom-approval-fill',
  'icon-wisdom-approval-line',
  'icon-wisdom-warehouse-fill',
  'icon-wisdom-warehouse-line',
  'icon-wisdom-refuse-fill',
  'icon-wisdom-refuse-line',
  'icon-wisdom-stock-fill',
  'icon-wisdom-stock-line',
  'icon-wisdom-final-process-fill',
  'icon-wisdom-final-process-line',
  'icon-wisdom-theme-fill',
  'icon-wisdom-theme-line',
  'icon-wisdom-transfer-fill',
  'icon-wisdom-transfer-line',
];
